- name: Install postfix to send alert emails
  dnf:
    name: postfix
    state: latest

- name: enable and start postfix
  systemd:
    name: postfix
    state: started
    enabled: yes

- name: install dnf automatic
  dnf:
    name: dnf-automatic
    state: latest

- name: dnf-automatic
  copy:
    src: files/dnf-automatic.conf
    dest: /etc/dnf/automatic.conf
    owner: root
    group: root
    mode: 0644

- name: enable a timer for dnf-automatic
  systemd:
    name: dnf-automatic.timer
    state: started
    enabled: yes
