- name: Install postfix to send alert emails
  dnf:
    name: postfix
    state: latest
    
- name: install dnf automatic
  dnf:
    name: dnf-automatic
    state: latest

- name: dnf-automatic
  copy:
    src: files/dnf-automatic.conf
    dest: /etc/automatic.conf
    owner: root
    group: root
    mode: 0644
