- file:
    path: /var/go/.ssh/id_rsa
    state: touch
    mode: 0600
    owner: go
    group: go


- name: place private gocd agent key in go home directory
  shell: credstash -r eu-west-1 get ssh/gocd-agent > /var/go/.ssh/id_rsa
