- copy:
    src: ../files/docker-conf.yaml
    dest: /etc/datadog-agent/conf.d/docker.d/conf.yaml
    owner: dd-agent
    group: dd-agent
    mode: 0644

# Excluded shm & netns mount points from DataDog agent disk monitoring.
# No metrics can be obtained from these and having them included causes excessive error logging.
- copy:
    src: ../files/docker-disk.yaml
    dest: /etc/datadog-agent/conf.d/disk.d/conf.yaml.default
    owner: dd-agent
    group: dd-agent
    mode: 0644


- service:
    name: datadog-agent
    state: restarted


- shell: usermod -aG docker dd-agent
- shell: usermod -aG root dd-agent
