environments:
  Ansible:
    pipelines:
      - base
      - elkstack
      - gocd-ansible
      - httpd-proxy
      - patching

pipelines:
  gocd-ansible:
    group: Ansible
    label_template: "${COUNT}"
    materials:
      mygit:
        git: https://github.com/ukparliament/uk.parliament-ansible.git
        branch: master
    stages:
      - build:
          clean_workspace: true
          jobs:
            default:
              tasks:
                - exec:
                    command: ansible-playbook
                    arguments:
                      - "-v"
                      - gocd-ansible/gocd-ansible-agent.yml
                      - "-f"
                      - 10
  elkstack:
    group: Ansible
    label_template: "${COUNT}"
    materials:
      mygit:
        git: https://github.com/ukparliament/uk.parliament-ansible.git
        branch: master
    stages:
      - build:
          clean_workspace: true
          jobs:
            default:
              tasks:
                - exec:
                    command: ansible-playbook
                    arguments:
                      - "-v"
                      - elkstack/main-common.yml
                      - "-f"
                      - 10
  base:
    group: Ansible
    label_template: "${COUNT}"
    materials:
      mygit:
        git: https://github.com/ukparliament/uk.parliament-ansible.git
        branch: master
    timer:
      spec: "0 0/30 * * * ?"
      only_on_changes: no
    stages:
      - build:
          clean_workspace: true
          jobs:
            default:
              tasks:
                - exec:
                    command: ansible-playbook
                    arguments:
                      - "-v"
                      - base/base-common.yml
                      - "-f"
                      - 10




  httpd-proxy:
   group: Ansible
   label_template: "${COUNT}"
   materials:
     mygit:
       git: https://github.com/ukparliament/uk.parliament-ansible.git
       branch: master
   stages:
     - build:
         clean_workspace: true
         jobs:
           default:
             tasks:
               - exec:
                   command: ansible-playbook
                   arguments:
                     - "-v"
                     - httpd-proxy/httpd-proxy.yml
                     - "-f"
                     - 10
  patching:
    group: ansible
    label_template: "${COUNT}"
    materials:
      mygit:
        git: https://github.com/ukparliament/uk.parliament-ansible.git
        branch: master
    stages:
      - build:
          clean_workspace: true
          jobs:
            default:
              tasks:
                - exec:
                    command: ansible-playbook
                    arguments:
                      - "-v"
                      - patching/patching-common.yml
                      - "-f"
                      - 10
