environments:
  Ansible:
    pipelines:
      - base
      - wordpress

pipelines:
  
  base:
    group: Ansible
    label_template: "${COUNT}"
    materials:
      mygit:
        git: https://github.com/ukparliament/uk.parliament-ansible.git
        branch: master
    timer:
      spec: "0 0/30 * * * ?"
      only_on_changes: no
    stages:
      - build:
          clean_workspace: true
          jobs:
            default:
              tasks:
                - exec:
                    command: ansible-playbook
                    arguments:
                      - base/base-web1live.yml
                      - "-f"
                      - 10

  wordpress:
    group: Ansible
    label_template: "${COUNT}"
    materials:
      mygit:
        git: https://github.com/ukparliament/uk.parliament-ansible.git
        branch: master
    stages:
      - build:
          clean_workspace: true
          jobs:
            default:
              tasks:
                - exec:
                    command: ansible-playbook
                    arguments:
                      - wordpress/wordpress.yml
                      - "-f"
                      - 10
