- hosts:   tag_Name_core_bastion_host tag_Name_ecs_bastion_host common-httpd-proxy-1 common-nginx-proxy-1 key_core_instances:!tag_Name_core_nginx_proxy_1:!tag_group_freeipa_servers:!tag_Name_core_httpd_proxy_1

  user: deployer
  become: yes
  become_method: sudo

  roles:
    - role: ubuntu-common
    - role: core-ubuntu


- hosts: tag_group_freeipa_servers

  user: deployer
  become: yes
  become_method: sudo

  roles:
    - role: core-fedora
