- hosts: key_core_instances tag_Name_core_bastion_host* tag_Name_ecs_bastion_host* key_ecs_instances:!tag_aws_autoscaling_groupName_ecs_cluster
  user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - role: packages-ubuntu
    - role: users
    - role: filebeat-ubuntu
    - role: hosts

- hosts: tag_Name_core_gocd_agent_ansible_1
  user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - role: gocd-agent-ansible

- hosts: key_core_instances key_ecs_instances:!tag_aws_autoscaling_groupName_ecs_cluster
  vars:
    freeipa_system_user: "{{credstash_freeipa_output.stdout}}"
    datadog_api_key: "{{credstash_query_output.stdout}}"
    datadog_config:
      hostname: "{{ ec2_tag_Account}}-{{ ec2_tag_Name }}-{{ inventory_hostname}}"
      tags: "devci"
  user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - role: datadog

- hosts: tag_aws_autoscaling_groupName_ecs_apps_cluster
  user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - role: datadog-nginx-router

- hosts: key_ecs_instances:!tag_Name_ecs_node
  vars:
    datadog_api_key: "{{credstash_query_output.stdout}}"
    datadog_config:
      hostname: "{{ ec2_tag_Account}}-{{ ec2_tag_Name }}-{{ inventory_hostname}}"
  user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - role: datadog-docker
    - role: filebeat-ecs


- hosts: key_ecs_instances:!tag_aws_autoscaling_groupName_ecs_cluster  tag_Name_core_bastion_host* tag_Name_ecs_bastion_host* key_core_instances:!tag_Application_second_reading
  vars:
    freeipa_system_user: "{{credstash_freeipa_output.stdout}}"
  user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - role: freeipa-client

- hosts: tag_Name_core_bastion_host* tag_Name_ecs_bastion_host*
  user: ubuntu
  become: yes
  become_method: sudo
  roles:
    - role: openvpn

- hosts: tag_Name_core_gocd_agent_ansible_1 tag_role_core_gocd_agent
  vars:
    freeipa_system_user: "{{credstash_freeipa_output.stdout}}"

  user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - role: packer


- hosts: tag_Application_second_reading
  vars:
    freeipa_system_user: "{{credstash_freeipa_output.stdout}}"
  user: ubuntu
  become: yes
  become_method: sudo
  roles:
    - role: filebeat-bitnami-wordpress
    - role: freeipa-client

- hosts: tag_InstallNode_yes
  vars:
    NODEJS_VERSION: "8"
  user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - role: nodejs


- hosts: tag_role_core_gocd_agent
  user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - role: gocd-agent
